version: 2

project_name: mermaid-go-renderer

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: mmdg
    main: ./cmd/mmdg
    binary: mmdg
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  use: git

brews:
  - repository:
      owner: bvolpato
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: mmdg
    commit_author:
      name: Bruno Volpato
      email: brunocvcunha@gmail.com
    directory: Formula
    homepage: "https://github.com/bvolpato/mermaid-go-renderer"
    description: "Native Mermaid renderer in Go without browser/chromium"
    license: "MIT"
    test: |
      (testpath/"diagram.mmd").write("flowchart LR\nA --> B\n")
      system "#{bin}/mmdg", "-i", testpath/"diagram.mmd", "-o", testpath/"out.svg", "-e", "svg"
      assert_predicate testpath/"out.svg", :exist?

